# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-31 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventattendance',
            options={'verbose_name_plural': 'Event Attendance'},
        ),
    ]
