# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='worship_leader',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
