# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-04 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180426_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='account_members.MemberProfile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='worship_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worship_leader', to='account_members.MemberProfile'),
        ),
    ]
