# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-11 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'verbose_name_plural': 'Feast Members'},
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
