# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_members', '0004_auto_20180311_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=8),
        ),
    ]
