# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_members', '0005_auto_20180325_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministry',
            name='ministry_type',
        ),
        migrations.RemoveField(
            model_name='ministrymember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='ministrymember',
            name='member_type',
        ),
        migrations.RemoveField(
            model_name='ministrymember',
            name='ministry',
        ),
        migrations.DeleteModel(
            name='Ministry',
        ),
        migrations.DeleteModel(
            name='MinistryMember',
        ),
        migrations.DeleteModel(
            name='MinistryType',
        ),
    ]
