# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministry_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministry',
            options={'verbose_name_plural': 'Ministries'},
        ),
        migrations.AlterField(
            model_name='ministrymember',
            name='member_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_member_type', to='account_members.MemberType'),
        ),
    ]
