# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministry_group', '0002_auto_20180325_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryMemberGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry', to='ministry_group.Ministry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ministrymember',
            name='ministry',
        ),
        migrations.AddField(
            model_name='ministrymembergroup',
            name='ministry_member',
            field=models.ManyToManyField(to='ministry_group.MinistryMember'),
        ),
    ]
