# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-31 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry_group', '0003_auto_20180325_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
